drop database if exists baseball_season;
create database baseball_season;
use baseball_season;

create table PLAYER (
	 ID INT auto_increment NOT NULL,
   LAST_NAME VARCHAR(25)  NOT NULL,
   FIRST_NAME VARCHAR(25)  NULL,
   TIMES_IN_PREMIUM  INT   NULL,
   PRIMARY KEY (id)
);

create table GAME (
  ID INT NOT NULL auto_increment,
  DATE_PLAYER DATE NOT NULL ,
  LOCATION VARCHAR(25) NULL,
  PRIMARY KEY (id)
);

create table INNING (
	 INNING_NUMBER INT NOT NULL,
   GAME_ID INT NOT NULL,
   PLAYER_ID INT NOT NULL,
   FIELD_POSITION VARCHAR(20) NOT NULL,
   PRIMARY KEY (INNING_NUMBER, GAME_ID, PLAYER_ID),
   FOREIGN KEY (GAME_ID) REFERENCES GAME(ID),
   FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID)
);

INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Ziring', 'Gavin', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Chermela', 'Nathan', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Silvotti', 'Chris', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Johson', 'Miles', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Smith', 'Brendan', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Player', 'Elliot', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Player', 'Jay', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Mouse', 'Mickey', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Duck', 'Donald', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Neutron', 'Jimmy', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Clause', 'Santa', 1);
INSERT INTO PLAYER (LAST_NAME, FIRST_NAME, TIMES_IN_PREMIUM) VALUES ('Frost', 'Jack', 1);

commit;